// prisma/seeds/03_reading_materials.ts
import type { Prisma, PrismaClient } from '@prisma/client';

type TransactionClient = Omit<PrismaClient, "$connect" | "$disconnect" | "$on" | "$transaction" | "$use" | "$extends">;

const readingMaterialsData: Prisma.reading_materialsCreateInput[] = [
    { material_id: 1, judul: 'Tata Laksana Penyelenggaraan Statistik', kategori: 'Pembinaan Statistik', sub_kategori: 'Dasar Penyelenggaraan Statistik', deskripsi: 'Panduan lengkap tata laksana penyelenggaraan statistik sesuai standar BPS.', file_path: 'Modul 1. Tata Laksana Penyelenggaraan Statistik.pdf', uploader: { connect: { user_id: 9 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 733, slug: 'tata-laksana-penyelenggaraan-statistik-1', bacaUrl: '/baca/tata-laksana-penyelenggaraan-statistik-1', unduhUrl: '/unduh/tata-laksana-penyelenggaraan-statistik-1' },
    { material_id: 2, judul: 'Langkah Praktis dalam Survei dan Kompromin', kategori: 'Pembinaan Statistik', sub_kategori: 'Dasar Penyelenggaraan Statistik', deskripsi: 'Teknik praktis yang diterapkan dalam survei serta koordinasi pemasaran dan informasi.', file_path: 'Modul 2. Langkah Praktis dalam Survei dan Kompromin.pdf', uploader: { connect: { user_id: 5 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 1418, slug: 'langkah-praktis-dalam-survei-dan-kompromin-2', bacaUrl: '/baca/langkah-praktis-dalam-survei-dan-kompromin-2', unduhUrl: '/unduh/langkah-praktis-dalam-survei-dan-kompromin-2' },
    { material_id: 3, judul: 'Aplikasi Penyelenggaraan Statistik', kategori: 'Pembinaan Statistik', sub_kategori: 'Dasar Penyelenggaraan Statistik', deskripsi: 'Modul tentang aplikasi yang digunakan dalam penyelenggaraan statistik.', file_path: 'Modul 3. Aplikasi Penyelenggaraan Statistik.pdf', uploader: { connect: { user_id: 8 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 470, slug: 'aplikasi-penyelenggaraan-statistik-3', bacaUrl: '/baca/aplikasi-penyelenggaraan-statistik-3', unduhUrl: '/unduh/aplikasi-penyelenggaraan-statistik-3' },
    { material_id: 4, judul: 'Dasar-dasar Statistik', kategori: 'Pembinaan Statistik', sub_kategori: 'Dasar Penyelenggaraan Statistik', deskripsi: 'Modul pengantar mengenai dasar-dasar ilmu statistik.', file_path: 'Modul 4. Dasar-dasar Statistik.pdf', uploader: { connect: { user_id: 5 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 1708, slug: 'dasar-dasar-statistik-4', bacaUrl: '/baca/dasar-dasar-statistik-4', unduhUrl: '/unduh/dasar-dasar-statistik-4' },
    { material_id: 5, judul: 'Teknik Sampling dan Pengolahan Data', kategori: 'Pembinaan Statistik', sub_kategori: 'Teknik Lanjutan', deskripsi: 'Penjelasan lengkap teknik sampling dan pengolahan data untuk hasil statistik yang valid.', file_path: 'modul_teknik_sampling.pdf', uploader: { connect: { user_id: 5 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 1278, slug: 'teknik-sampling-dan-pengolahan-data-5', bacaUrl: '/baca/teknik-sampling-dan-pengolahan-data-5', unduhUrl: '/unduh/teknik-sampling-dan-pengolahan-data-5' },
    { material_id: 6, judul: 'Metode Sensus dan Survei Terpadu', kategori: 'Metodologi Sensus & Survei', sub_kategori: 'Kerangka Kerja', deskripsi: 'Panduan metodologi sensus dan survei terpadu terbaru.', file_path: 'modul_metode_sensus.pdf', uploader: { connect: { user_id: 10 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 624, slug: 'metode-sensus-dan-survei-terpadu-6', bacaUrl: '/baca/metode-sensus-dan-survei-terpadu-6', unduhUrl: '/unduh/metode-sensus-dan-survei-terpadu-6' },
    { material_id: 7, judul: 'Teknik Pengolahan Data Sensus', kategori: 'Metodologi Sensus & Survei', sub_kategori: 'Kerangka Kerja', deskripsi: 'Teknik pengolahan dan validasi data hasil sensus.', file_path: 'modul_pengolahan_sensus.pdf', uploader: { connect: { user_id: 6 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 491, slug: 'teknik-pengolahan-data-sensus-7', bacaUrl: '/baca/teknik-pengolahan-data-sensus-7', unduhUrl: '/unduh/teknik-pengolahan-data-sensus-7' },
    { material_id: 8, judul: 'Paparan Hasil Survei Nasional Triwulan I', kategori: 'Dokumentasi Paparan', sub_kategori: 'Indikator Strategik', deskripsi: 'Paparan lengkap hasil survei nasional terbaru yang disampaikan oleh Kepala BPS.', file_path: 'x7qwnoe0ds029u3nky3hvq29w.pdf', uploader: { connect: { user_id: 8 } }, tanggal_upload: new Date('2024-01-15 03:00:00.000Z'), hits: 255, slug: 'paparan-hasil-survei-nasional-triwulan-i-1751588074128', bacaUrl: '/files/ruangbaca/x7qwnoe0ds029u3nky3hvq29w.pdf', unduhUrl: '/files/ruangbaca/x7qwnoe0ds029u3nky3hvq29w.pdf' },
    { material_id: 9, judul: '20161004 FGD BPS dengan Komisi XI DPR RI', kategori: 'Dokumentasi Paparan', sub_kategori: 'Indikator Strategis', deskripsi: 'Materi Fokus Group Discussion BPS dengan Komisi XI DPR RI.', file_path: '20161004 FGD BPS denganKomisi XI DPR RI.pdf', uploader: { connect: { user_id: 3 } }, tanggal_upload: new Date('2024-01-15 03:00:00.000Z'), hits: 213, slug: '20161004-fgd-bps-dengan-komisi-xi-dpr-ri-9', bacaUrl: '/baca/20161004-fgd-bps-dengan-komisi-xi-dpr-ri-9', unduhUrl: '/unduh/20161004-fgd-bps-dengan-komisi-xi-dpr-ri-9' },
    { material_id: 10, judul: '20161116 NTT Launching Satu Data Final', kategori: 'Dokumentasi Paparan', sub_kategori: 'Indikator Strategis', deskripsi: 'Paparan final peluncuran Satu Data di NTT.', file_path: '20161116 NTT Launching Satu Data_Final.pdf', uploader: { connect: { user_id: 4 } }, tanggal_upload: new Date('2024-01-15 03:00:00.000Z'), hits: 292, slug: '20161116-ntt-launching-satu-data-final-10', bacaUrl: '/baca/20161116-ntt-launching-satu-data-final-10', unduhUrl: '/unduh/20161116-ntt-launching-satu-data-final-10' },
    { material_id: 11, judul: 'Indikator Pembangunan Kalsel Nov 2016', kategori: 'Dokumentasi Paparan', sub_kategori: 'Indikator Strategis', deskripsi: 'Indikator pembangunan Kalimantan Selatan per November 2016.', file_path: 'Indikator Pembangunan Kalsel Nov 2016.pdf', uploader: { connect: { user_id: 10 } }, tanggal_upload: new Date('2024-01-15 03:00:00.000Z'), hits: 269, slug: 'indikator-pembangunan-kalsel-nov-2016-11', bacaUrl: '/baca/indikator-pembangunan-kalsel-nov-2016-11', unduhUrl: '/unduh/indikator-pembangunan-kalsel-nov-2016-11' },
    { material_id: 12, judul: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau', kategori: 'Dokumentasi Paparan', sub_kategori: 'Indikator Strategis', deskripsi: 'Paparan BPS Kabupaten Pulang Pisau untuk BPBD.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 11 } }, tanggal_upload: new Date('2024-01-15 03:00:00.000Z'), hits: 294, slug: 'paparan-bps-pulang-pisau-untuk-bpbd-kab-pulang-pisau-12', bacaUrl: '/baca/paparan-bps-pulang-pisau-untuk-bpbd-kab-pulang-pisau-12', unduhUrl: '/unduh/paparan-bps-pulang-pisau-untuk-bpbd-kab-pulang-pisau-12' },
    { material_id: 14, judul: 'Metodologi Monitoring dan Evaluasi Program', kategori: 'Monitoring & Evaluasi', sub_kategori: 'Metodologi & Pelaporan', deskripsi: 'Pendekatan dan teknik monitoring dan evaluasi program statistik.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 8 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 294, slug: 'metodologi-monitoring-dan-evaluasi-program-14', bacaUrl: '/baca/metodologi-monitoring-dan-evaluasi-program-14', unduhUrl: '/unduh/metodologi-monitoring-dan-evaluasi-program-14' },
    { material_id: 15, judul: 'Evaluasi Aktivitas Internal BPS', kategori: 'Monitoring & Evaluasi', sub_kategori: 'Metodologi & Pelaporan', deskripsi: 'Monitoring dan evaluasi aktivitas serta kinerja internal BPS secara menyeluruh.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 2 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 275, slug: 'evaluasi-aktivitas-internal-bps-15', bacaUrl: '/baca/evaluasi-aktivitas-internal-bps-15', unduhUrl: '/unduh/evaluasi-aktivitas-internal-bps-15' },
    { material_id: 16, judul: 'Standar Biaya Masukan (SBM) Tahun Anggaran 2023', kategori: 'Standar Biaya', sub_kategori: 'SBM & Operasional', deskripsi: 'Dokumen resmi terkait standar biaya masukan untuk kegiatan.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 6 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 1489, slug: 'standar-biaya-masukan-sbm-tahun-anggaran-2023-16', bacaUrl: '/baca/standar-biaya-masukan-sbm-tahun-anggaran-2023-16', unduhUrl: '/unduh/standar-biaya-masukan-sbm-tahun-anggaran-2023-16' },
    { material_id: 17, judul: 'Dasar-dasar Akuntabilitas Kinerja', kategori: 'Akuntabilitas Kinerja', sub_kategori: 'Kinerja & Pelaporan', deskripsi: 'Pengertian dan prinsip utama sistem akuntabilitas kinerja di instansi pemerintah.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 9 } }, tanggal_upload: new Date('2024-01-15 03:00:00.000Z'), hits: 423, slug: 'dasar-dasar-akuntabilitas-kinerja-17', bacaUrl: '/baca/dasar-dasar-akuntabilitas-kinerja-17', unduhUrl: '/unduh/dasar-dasar-akuntabilitas-kinerja-17' },
    { material_id: 18, judul: 'Panduan Implementasi SAKIP', kategori: 'Akuntabilitas Kinerja', sub_kategori: 'Kinerja & Pelaporan', deskripsi: 'Panduan penerapan Sistem Akuntabilitas Kinerja Instansi Pemerintah (SAKIP).', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 3 } }, tanggal_upload: new Date('2024-01-15 03:00:00.000Z'), hits: 252, slug: 'panduan-implementasi-sakip-18', bacaUrl: '/baca/panduan-implementasi-sakip-18', unduhUrl: '/unduh/panduan-implementasi-sakip-18' },
    { material_id: 19, judul: 'Strategi Diseminasi Statistik Digital', kategori: 'Diseminasi Statistik', sub_kategori: 'Strategi & Praktik', deskripsi: 'Strategi diseminasi dan publikasi hasil statistik ke publik secara efektif melalui kanal digital.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 8 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 277, slug: 'strategi-diseminasi-statistik-digital-19', bacaUrl: '/baca/strategi-diseminasi-statistik-digital-19', unduhUrl: '/unduh/strategi-diseminasi-statistik-digital-19' },
    { material_id: 20, judul: 'Materi Pelatihan Kepemimpinan Statistik', kategori: 'Leadership & Manajemen', sub_kategori: 'Pelatihan Kepemimpinan', deskripsi: 'Kumpulan materi pelatihan dan pengembangan kepemimpinan bagi staf statistik.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 1 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 271, slug: 'materi-pelatihan-kepemimpinan-statistik-20', bacaUrl: '/baca/materi-pelatihan-kepemimpinan-statistik-20', unduhUrl: '/unduh/materi-pelatihan-kepemimpinan-statistik-20' },
    { material_id: 21, judul: 'Best Practices: Leading National Statistics Office', kategori: 'Leadership & Manajemen', sub_kategori: 'Pelatihan Kepemimpinan', deskripsi: 'Studi kasus dan strategi efektif dalam memimpin kantor statistik nasional di era modern.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 9 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 224, slug: 'best-practices-leading-national-statistics-office-21', bacaUrl: '/baca/best-practices-leading-national-statistics-office-21', unduhUrl: '/unduh/best-practices-leading-national-statistics-office-21' },
    { material_id: 22, judul: 'Technical Assistance ABS', kategori: 'Asistensi Teknis', sub_kategori: 'Bantuan Teknis', deskripsi: 'Dokumentasi dan materi bantuan teknis untuk pelaksanaan statistik berbasis sampel (ABS).', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 11 } }, tanggal_upload: new Date('2024-01-15 03:00:00.000Z'), hits: 144, slug: 'technical-assistance-abs-1751587374483', bacaUrl: '/baca/technical-assistance-abs-22', unduhUrl: '/unduh/technical-assistance-abs-22' },
    { material_id: 23, judul: 'Materi Seminar Pelayanan Publik', kategori: 'Seminar & Workshop', sub_kategori: 'Materi Seminar', deskripsi: 'Materi dan laporan dari seminar pelayanan publik terbaru yang diselenggarakan oleh BPS.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 5 } }, tanggal_upload: new Date('2024-01-15 03:00:00.000Z'), hits: 168, slug: 'materi-seminar-pelayanan-publik-23', bacaUrl: '/baca/materi-seminar-pelayanan-publik-23', unduhUrl: '/unduh/materi-seminar-pelayanan-publik-23' },
    { material_id: 25, judul: 'Dasar-Dasar Reformasi Birokrasi', kategori: 'Reformasi Birokrasi', sub_kategori: 'Panduan & Implementasi', deskripsi: 'Konsep dan prinsip reformasi birokrasi di instansi pemerintah.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 3 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 152, slug: 'dasar-dasar-reformasi-birokrasi-25', bacaUrl: '/baca/dasar-dasar-reformasi-birokrasi-25', unduhUrl: '/unduh/dasar-dasar-reformasi-birokrasi-25' },
    { material_id: 26, judul: 'Implementasi Reformasi Birokrasi di BPS', kategori: 'Reformasi Birokrasi', sub_kategori: 'Panduan & Implementasi', deskripsi: 'Langkah-langkah dan studi kasus pelaksanaan reformasi birokrasi di lingkungan BPS.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 9 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 163, slug: 'implementasi-reformasi-birokrasi-di-bps-26', bacaUrl: '/baca/implementasi-reformasi-birokrasi-di-bps-26', unduhUrl: '/unduh/implementasi-reformasi-birokrasi-di-bps-26' },
    { material_id: 27, judul: 'Undang-Undang Statistik No. 16 Tahun 1997', kategori: 'Regulasi', sub_kategori: 'Hukum & Peraturan', deskripsi: 'Teks lengkap dan penjelasan regulasi dasar yang mengatur penyelenggaraan statistik nasional.', file_path: 'Paparan BPS Pulang Pisau untuk BPBD Kab. Pulang Pisau.pdf', uploader: { connect: { user_id: 9 } }, tanggal_upload: new Date('2023-01-15 03:00:00.000Z'), hits: 1713, slug: 'undang-undang-statistik-no-16-tahun-1997-27', bacaUrl: '/baca/undang-undang-statistik-no-16-tahun-1997-27', unduhUrl: '/unduh/undang-undang-statistik-no-16-tahun-1997-27' },
];

export async function seedReadingMaterials(tx: TransactionClient) {
    console.log(`-> Memasukkan data bahan bacaan...`);
    await tx.reading_materials.deleteMany({});

    for (const material of readingMaterialsData) {
        await tx.reading_materials.create({
            data: material,
        });
    }
    console.log(`  ✅ Seeded ${readingMaterialsData.length} reading materials.`);
}

// Menambahkan `export {}` untuk menjadikan file ini sebagai module
export {};
