// prisma/seeds/01_organization_users.ts
import { PrismaClient, Prisma } from '@prisma/client';

export async function seedOrganizationAndUsers(prisma: PrismaClient) {
  console.log(`--- Seeding organization_units and users ---`);

  // --- Seed organization_units ---
  const organizationUnitsData: Prisma.organization_unitsCreateInput[] = [
    { org_unit_id: 1, nama_wilayah: 'Nasional', kode_bps: '0000', nama_satker_bagian: 'BPS Pusat' },
    { org_unit_id: 2, nama_wilayah: 'Jawa Barat', kode_bps: '3200', nama_satker_bagian: 'BPS Provinsi Jawa Barat', parent: { connect: { org_unit_id: 1 } } },
    { org_unit_id: 3, nama_wilayah: 'Nasional', kode_bps: '0000', nama_satker_bagian: 'Bidang Teknologi Informasi', parent: { connect: { org_unit_id: 1 } } },
  ];

  for (const data of organizationUnitsData) {
    await prisma.organization_units.upsert({
      where: { org_unit_id: data.org_unit_id },
      update: data,
      create: data,
    });
  }
  console.log(`✅ Seeded organization_units.`);

  // --- Seed users ---
  const usersData: Prisma.usersCreateInput[] = [
    {
      user_id: 1,
      nama_lengkap: 'Arianto S.Si., SE., M.Si',
      nip_baru: '196911091991011001',
      nip_lama: '1969110919',
      email: 'arianto@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'user',
      sso_id: 'sso-dzke16rm0op',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('1969-11-08T00:00:00.000Z'),
      jenis_kelamin: 'Laki-laki',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('1990-12-31T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('1995-12-31T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('1997-12-31T00:00:00.000Z'),
      pendidikan_terakhir: 'SMA',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2027-11-08T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'B',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$SX9TQ/jJJUvTa.md/6.z.u6gOhvBgNL67vaU5BGpTDfzyFm3.0U5S',
      username: 'user1',
    },
    {
      user_id: 2,
      nama_lengkap: 'Siti Nurdjannah SST',
      nip_baru: '197012191993122001',
      nip_lama: '1970121919',
      email: 'snurdjan@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'user',
      sso_id: 'sso-31kx0nymx2q',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('1970-12-18T00:00:00.000Z'),
      jenis_kelamin: 'Perempuan',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('1993-11-30T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('1998-11-30T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2000-11-30T00:00:00.000Z'),
      pendidikan_terakhir: 'SMA',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2028-12-18T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'D',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$NzIq2Rsr3.1d39Iz53mpuOv2XQtK/JzECrjhKd3Gy/Fs8Wptq5F8C',
      username: 'user2',
    },
    {
      user_id: 3,
      nama_lengkap: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      nip_baru: '197607182011012003',
      nip_lama: '1976071820',
      email: 'sitinurlaela@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'user',
      sso_id: 'sso-qrotetlsh1',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('1976-07-17T00:00:00.000Z'),
      jenis_kelamin: 'Laki-laki',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('2010-12-31T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('2015-12-31T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2017-12-31T00:00:00.000Z'),
      pendidikan_terakhir: 'S2',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2034-07-17T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'D',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$qInPi9NumR.oYGZFohfzxuL4C2ZXoYnbOiyoEO0bsqAbAPkv36HVe',
      username: 'user3',
    },
    {
      user_id: 4,
      nama_lengkap: 'Achmad Muchlis Abdi Putra SST., MT',
      nip_baru: '198610142009021001',
      nip_lama: '1986101420',
      email: 'achmadmuchlis@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'admin',
      sso_id: 'sso-djykiyr53ip',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('1986-10-13T00:00:00.000Z'),
      jenis_kelamin: 'Laki-laki',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('2009-01-31T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('2014-01-31T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2016-01-31T00:00:00.000Z'),
      pendidikan_terakhir: 'D3',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2044-10-13T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'C',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$rKNJeHO9qU/smZinLVGaeeT1.VvmOqyKetaX.rYrBuPyVZHKfZ2EW',
      username: 'admin1',
    },
    {
      user_id: 5,
      nama_lengkap: 'Mohamad Rivani S.IP, M.M.',
      nip_baru: '198103042006041001',
      nip_lama: '1981030420',
      email: 'mohamad.rivani@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'user',
      sso_id: 'sso-f0ai52ewgzo',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('1981-03-03T00:00:00.000Z'),
      jenis_kelamin: 'Laki-laki',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('2006-03-31T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('2011-03-31T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2013-03-31T00:00:00.000Z'),
      pendidikan_terakhir: 'S1',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2039-03-03T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'C',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$NuuoWtCnXRzqRAI9lEBzBemls9/.c5s6d2PFceN9TTrekuO8.8FyW',
      username: 'user4',
    },
    {
      user_id: 6,
      nama_lengkap: 'Andri Saleh S.Si, M.I.Kom.',
      nip_baru: '198005162009021006',
      nip_lama: '1980051620',
      email: 'andris@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'user',
      sso_id: 'sso-yqsn5qcst2h',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('1980-05-15T00:00:00.000Z'),
      jenis_kelamin: 'Laki-laki',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('2009-01-31T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('2014-01-31T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2016-01-31T00:00:00.000Z'),
      pendidikan_terakhir: 'S1',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2038-05-15T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'D',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$Y8BHBRohX1HyMJAOD1EyKuAvqvLxnDs5DQ7l/UnCloYjjPMYIaL1e',
      username: 'user5',
    },
    {
      user_id: 7,
      nama_lengkap: 'Muhammad Haikal Candra S.Tr.Ds.',
      nip_baru: '199812162025061004',
      nip_lama: '1998121620',
      email: 'haikal.candra@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'user',
      sso_id: 'sso-vsonvyuulc',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('1998-12-15T00:00:00.000Z'),
      jenis_kelamin: 'Perempuan',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('2025-05-31T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('2030-05-31T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2032-05-31T00:00:00.000Z'),
      pendidikan_terakhir: 'D3',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2056-12-15T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'A',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$XUHrUUTieK8qApUBqChx.e26DrJ4Y5Vg3DT7k1tGU6r4BjMD6g2gK',
      username: 'user6',
    },
    {
      user_id: 8,
      nama_lengkap: 'Bagus Ardiansyah S.Tr.Stat.',
      nip_baru: '199605282019121001',
      nip_lama: '1996052820',
      email: 'bagus.ardi@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'user',
      sso_id: 'sso-pc6spkbw0va',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('1996-05-27T00:00:00.000Z'),
      jenis_kelamin: 'Laki-laki',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('2019-11-30T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('2024-11-30T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2026-11-30T00:00:00.000Z'),
      pendidikan_terakhir: 'S2',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2054-05-27T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'B',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$tyEKUM1Z3mkwaGsKmVrT2OJZGZOFaf.iDje2Y14RheIozitcfFzGS',
      username: 'user7',
    },
    {
      user_id: 9,
      nama_lengkap: 'Aliyah Salsabila Hakim S.Hum.',
      nip_baru: '200108122025062004',
      nip_lama: '2001081220',
      email: 'aliyah.salsabila@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'user',
      sso_id: 'sso-eiy0p3taf1a',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('2001-08-11T00:00:00.000Z'),
      jenis_kelamin: 'Laki-laki',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('2025-05-31T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('2030-05-31T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2032-05-31T00:00:00.000Z'),
      pendidikan_terakhir: 'S1',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2059-08-11T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'A',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$GW6MyLnh3AO6/hJQqwvfZOzeoYG200FRTlfZ8PMHq6kEM0h9h9Msy',
      username: 'user8',
    },
    {
      user_id: 10,
      nama_lengkap: 'Dira Afiani S.S.',
      nip_baru: '200009302025062005',
      nip_lama: '2000093020',
      email: 'dira.afiani@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'user',
      sso_id: 'sso-lw4qtd610oi',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('2000-09-29T00:00:00.000Z'),
      jenis_kelamin: 'Laki-laki',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('2025-05-31T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('2030-05-31T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2032-05-31T00:00:00.000Z'),
      pendidikan_terakhir: 'SMA',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2058-09-29T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'C',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$ADpJajulmvH.J3sklFJEKOPQ0F/N.Mxzl253deD6IyN7OYCc8/6d6',
      username: 'user9',
    },
    {
      user_id: 11,
      nama_lengkap: 'Aina Sabedah Fitri S.Si, MSE',
      nip_baru: '197709101999122001',
      nip_lama: '1977091019',
      email: 'aina@bps.go.id',
      // unit_kerja_id: null di dump, kita default ke org_unit_id 1
      unit_kerja: { connect: { org_unit_id: 1 } },
      role: 'admin',
      sso_id: 'sso-qn6kten948',
      foto_url: null,
      tempat_lahir: 'Jakarta',
      tanggal_lahir: new Date('1977-09-09T00:00:00.000Z'),
      jenis_kelamin: 'Perempuan',
      status_kepegawaian: 'PNS',
      tmt_pns: new Date('1999-11-30T00:00:00.000Z'),
      pangkat_golongan: 'Pembina Tk. I, III/b',
      tmt_pangkat_golongan: new Date('2004-11-30T00:00:00.000Z'),
      jabatan_struktural: 'Kepala Bagian',
      jenjang_jabatan_fungsional: 'Pranata Komputer Madya',
      tmt_jabatan: new Date('2006-11-30T00:00:00.000Z'),
      pendidikan_terakhir: 'SMA',
      masa_kerja_golongan: '10 Tahun',
      masa_kerja_total: '20 Tahun',
      tanggal_pensiun: new Date('2035-09-09T00:00:00.000Z'),
      sisa_masa_kerja: '5 Tahun',
      grade: 'C',
      unit_kerja_eselon1: 'Sekretariat Utama',
      unit_kerja_eselon2: 'Biro Hubungan Masyarakat dan Hukum',
      password: '$2b$10$l6wasOijORgKX6ayix.JGeoRkL2sjhJa54EvI.5wqn.TuHGRn6z5W',
      username: 'admin2',
    },
  ];

  for (const data of usersData) {
    await prisma.users.upsert({
      where: { user_id: data.user_id },
      update: data,
      create: data,
    });
  }
  console.log(`✅ Seeded users.`);
}