// prisma/seeds/02_news_materials.ts
import { PrismaClient, Prisma } from '@prisma/client';

export async function seedNewsAndMaterials(prisma: PrismaClient) {
  console.log(`--- Seeding news and reading_materials ---`);

  // --- Seed news ---
  const newsData: Prisma.newsCreateInput[] = [
    {
      news_id: 1,
      judul: 'Wisata: Analisis Mendalam Topik ke-1',
      kategori: 'Wisata',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-1. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Mohamad Rivani S.IP, M.M.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+1' }],
      createdAt: new Date('2025-07-04T03:24:08.334Z'),
      penulis: { connect: { user_id: 5 } },
      publishedAt: new Date('2025-03-27T03:24:08.329Z'),
      savedAt: new Date('2025-03-27T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.334Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-1". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 2,
      judul: 'Opini: Analisis Mendalam Topik ke-2',
      kategori: 'Opini',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-2. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+2' }],
      createdAt: new Date('2025-07-04T03:24:08.364Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-03-28T03:24:08.329Z'),
      savedAt: new Date('2025-03-28T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.364Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-2". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 3,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-3',
      kategori: 'Fotogenik',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-3. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+3' }],
      createdAt: new Date('2025-07-04T03:24:08.368Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-03-29T03:24:08.329Z'),
      savedAt: new Date('2025-03-29T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.368Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-3". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 4,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-4',
      kategori: 'Serba Serbi',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-4. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Muhammad Haikal Candra S.Tr.Ds.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+4' }],
      createdAt: new Date('2025-07-04T03:24:08.370Z'),
      penulis: { connect: { user_id: 7 } },
      publishedAt: new Date('2025-03-30T03:24:08.329Z'),
      savedAt: new Date('2025-03-30T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.370Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-4". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 5,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-5',
      kategori: 'Berita Daerah',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-5. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+5' }],
      createdAt: new Date('2025-07-04T03:24:08.373Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-03-31T03:24:08.329Z'),
      savedAt: new Date('2025-03-31T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.373Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-5". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 6,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-6',
      kategori: 'BPS Terkini',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-6. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+6' }],
      createdAt: new Date('2025-07-04T03:24:08.374Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-04-01T03:24:08.329Z'),
      savedAt: new Date('2025-04-01T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.374Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-6". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 7,
      judul: 'Wisata: Analisis Mendalam Topik ke-7',
      kategori: 'Wisata',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-7. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aina Sabedah Fitri S.Si, MSE',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+7' }],
      createdAt: new Date('2025-07-04T03:24:08.376Z'),
      penulis: { connect: { user_id: 11 } },
      publishedAt: new Date('2025-04-02T03:24:08.329Z'),
      savedAt: new Date('2025-04-02T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.376Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-7". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 8,
      judul: 'Opini: Analisis Mendalam Topik ke-8',
      kategori: 'Opini',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-8. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+8' }],
      createdAt: new Date('2025-07-04T03:24:08.378Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-04-03T03:24:08.329Z'),
      savedAt: new Date('2025-04-03T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.378Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-8". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 9,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-9',
      kategori: 'Fotogenik',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-9. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nurdjannah SST',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+9' }],
      createdAt: new Date('2025-07-04T03:24:08.379Z'),
      penulis: { connect: { user_id: 2 } },
      publishedAt: new Date('2025-04-04T03:24:08.329Z'),
      savedAt: new Date('2025-04-04T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.379Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-9". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 10,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-10',
      kategori: 'Serba Serbi',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-10. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+10' }],
      createdAt: new Date('2025-07-04T03:24:08.380Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-04-05T03:24:08.329Z'),
      savedAt: new Date('2025-04-05T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.380Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-10". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 11,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-11',
      kategori: 'Berita Daerah',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-11. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+11' }],
      createdAt: new Date('2025-07-04T03:24:08.381Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-04-06T03:24:08.329Z'),
      savedAt: new Date('2025-04-06T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.381Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-11". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 12,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-12',
      kategori: 'BPS Terkini',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-12. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nurdjannah SST',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+12' }],
      createdAt: new Date('2025-07-04T03:24:08.382Z'),
      penulis: { connect: { user_id: 2 } },
      publishedAt: new Date('2025-04-07T03:24:08.329Z'),
      savedAt: new Date('2025-04-07T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.382Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-12". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 13,
      judul: 'Wisata: Analisis Mendalam Topik ke-13',
      kategori: 'Wisata',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-13. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aina Sabedah Fitri S.Si, MSE',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+13' }],
      createdAt: new Date('2025-07-04T03:24:08.383Z'),
      penulis: { connect: { user_id: 11 } },
      publishedAt: new Date('2025-04-08T03:24:08.329Z'),
      savedAt: new Date('2025-04-08T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.383Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-13". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 14,
      judul: 'Opini: Analisis Mendalam Topik ke-14',
      kategori: 'Opini',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-14. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+14' }],
      createdAt: new Date('2025-07-04T03:24:08.384Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-04-09T03:24:08.329Z'),
      savedAt: new Date('2025-04-09T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.384Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-14". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 15,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-15',
      kategori: 'Fotogenik',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-15. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+15' }],
      createdAt: new Date('2025-07-04T03:24:08.385Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-04-10T03:24:08.329Z'),
      savedAt: new Date('2025-04-10T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.385Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-15". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 16,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-16',
      kategori: 'Serba Serbi',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-16. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+16' }],
      createdAt: new Date('2025-07-04T03:24:08.385Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-04-11T03:24:08.329Z'),
      savedAt: new Date('2025-04-11T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.385Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-16". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 17,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-17',
      kategori: 'Berita Daerah',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-17. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Muhammad Haikal Candra S.Tr.Ds.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+17' }],
      createdAt: new Date('2025-07-04T03:24:08.387Z'),
      penulis: { connect: { user_id: 7 } },
      publishedAt: new Date('2025-04-12T03:24:08.329Z'),
      savedAt: new Date('2025-04-12T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.387Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-17". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 18,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-18',
      kategori: 'BPS Terkini',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-18. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aina Sabedah Fitri S.Si, MSE',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+18' }],
      createdAt: new Date('2025-07-04T03:24:08.388Z'),
      penulis: { connect: { user_id: 11 } },
      publishedAt: new Date('2025-04-13T03:24:08.329Z'),
      savedAt: new Date('2025-04-13T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.388Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-18". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 19,
      judul: 'Wisata: Analisis Mendalam Topik ke-19',
      kategori: 'Wisata',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-19. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+19' }],
      createdAt: new Date('2025-07-04T03:24:08.389Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-04-14T03:24:08.329Z'),
      savedAt: new Date('2025-04-14T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.389Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-19". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 20,
      judul: 'Opini: Analisis Mendalam Topik ke-20',
      kategori: 'Opini',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-20. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Muhammad Haikal Candra S.Tr.Ds.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+20' }],
      createdAt: new Date('2025-07-04T03:24:08.390Z'),
      penulis: { connect: { user_id: 7 } },
      publishedAt: new Date('2025-04-15T03:24:08.329Z'),
      savedAt: new Date('2025-04-15T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.390Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-20". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 21,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-21',
      kategori: 'Fotogenik',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-21. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Andri Saleh S.Si, M.I.Kom.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+21' }],
      createdAt: new Date('2025-07-04T03:24:08.391Z'),
      penulis: { connect: { user_id: 6 } },
      publishedAt: new Date('2025-04-16T03:24:08.329Z'),
      savedAt: new Date('2025-04-16T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.391Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-21". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 22,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-22',
      kategori: 'Serba Serbi',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-22. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+22' }],
      createdAt: new Date('2025-07-04T03:24:08.391Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-04-17T03:24:08.329Z'),
      savedAt: new Date('2025-04-17T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.391Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-22". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 23,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-23',
      kategori: 'Berita Daerah',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-23. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Mohamad Rivani S.IP, M.M.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+23' }],
      createdAt: new Date('2025-07-04T03:24:08.392Z'),
      penulis: { connect: { user_id: 5 } },
      publishedAt: new Date('2025-04-18T03:24:08.329Z'),
      savedAt: new Date('2025-04-18T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.392Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-23". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 24,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-24',
      kategori: 'BPS Terkini',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-24. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Dira Afiani S.S.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+24' }],
      createdAt: new Date('2025-07-04T03:24:08.392Z'),
      penulis: { connect: { user_id: 10 } },
      publishedAt: new Date('2025-04-19T03:24:08.329Z'),
      savedAt: new Date('2025-04-19T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.392Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-24". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 25,
      judul: 'Wisata: Analisis Mendalam Topik ke-25',
      kategori: 'Wisata',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-25. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+25' }],
      createdAt: new Date('2025-07-04T03:24:08.393Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-04-20T03:24:08.329Z'),
      savedAt: new Date('2025-04-20T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.393Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-25". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 26,
      judul: 'Opini: Analisis Mendalam Topik ke-26',
      kategori: 'Opini',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-26. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Muhammad Haikal Candra S.Tr.Ds.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+26' }],
      createdAt: new Date('2025-07-04T03:24:08.394Z'),
      penulis: { connect: { user_id: 7 } },
      publishedAt: new Date('2025-04-21T03:24:08.329Z'),
      savedAt: new Date('2025-04-21T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.394Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-26". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 27,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-27',
      kategori: 'Fotogenik',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-27. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+27' }],
      createdAt: new Date('2025-07-04T03:24:08.403Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-04-22T03:24:08.329Z'),
      savedAt: new Date('2025-04-22T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.403Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-27". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 28,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-28',
      kategori: 'Serba Serbi',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-28. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+28' }],
      createdAt: new Date('2025-07-04T03:24:08.403Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-04-23T03:24:08.329Z'),
      savedAt: new Date('2025-04-23T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.403Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-28". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 29,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-29',
      kategori: 'Berita Daerah',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-29. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+29' }],
      createdAt: new Date('2025-07-04T03:24:08.404Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-04-24T03:24:08.329Z'),
      savedAt: new Date('2025-04-24T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.404Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-29". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 30,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-30',
      kategori: 'BPS Terkini',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-30. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nurdjannah SST',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+30' }],
      createdAt: new Date('2025-07-04T03:24:08.405Z'),
      penulis: { connect: { user_id: 2 } },
      publishedAt: new Date('2025-04-25T03:24:08.329Z'),
      savedAt: new Date('2025-04-25T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.405Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-30". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 31,
      judul: 'Wisata: Analisis Mendalam Topik ke-31',
      kategori: 'Wisata',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-31. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+31' }],
      createdAt: new Date('2025-07-04T03:24:08.406Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-04-26T03:24:08.329Z'),
      savedAt: new Date('2025-04-26T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.406Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-31". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 32,
      judul: 'Opini: Analisis Mendalam Topik ke-32',
      kategori: 'Opini',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-32. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+32' }],
      createdAt: new Date('2025-07-04T03:24:08.407Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-04-27T03:24:08.329Z'),
      savedAt: new Date('2025-04-27T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.407Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-32". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 33,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-33',
      kategori: 'Fotogenik',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-33. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+33' }],
      createdAt: new Date('2025-07-04T03:24:08.408Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-04-28T03:24:08.329Z'),
      savedAt: new Date('2025-04-28T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.408Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-33". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 34,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-34',
      kategori: 'Serba Serbi',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-34. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nurdjannah SST',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+34' }],
      createdAt: new Date('2025-07-04T03:24:08.408Z'),
      penulis: { connect: { user_id: 2 } },
      publishedAt: new Date('2025-04-29T03:24:08.329Z'),
      savedAt: new Date('2025-04-29T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.408Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-34". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 35,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-35',
      kategori: 'Berita Daerah',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-35. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+35' }],
      createdAt: new Date('2025-07-04T03:24:08.409Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-04-30T03:24:08.329Z'),
      savedAt: new Date('2025-04-30T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.409Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-35". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 36,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-36',
      kategori: 'BPS Terkini',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-36. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+36' }],
      createdAt: new Date('2025-07-04T03:24:08.410Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-05-01T03:24:08.329Z'),
      savedAt: new Date('2025-05-01T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.410Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-36". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 37,
      judul: 'Wisata: Analisis Mendalam Topik ke-37',
      kategori: 'Wisata',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-37. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Andri Saleh S.Si, M.I.Kom.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+37' }],
      createdAt: new Date('2025-07-04T03:24:08.410Z'),
      penulis: { connect: { user_id: 6 } },
      publishedAt: new Date('2025-05-02T03:24:08.329Z'),
      savedAt: new Date('2025-05-02T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.410Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-37". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 38,
      judul: 'Opini: Analisis Mendalam Topik ke-38',
      kategori: 'Opini',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-38. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Andri Saleh S.Si, M.I.Kom.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+38' }],
      createdAt: new Date('2025-07-04T03:24:08.411Z'),
      penulis: { connect: { user_id: 6 } },
      publishedAt: new Date('2025-05-03T03:24:08.329Z'),
      savedAt: new Date('2025-05-03T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.411Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-38". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 39,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-39',
      kategori: 'Fotogenik',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-39. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Dira Afiani S.S.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+39' }],
      createdAt: new Date('2025-07-04T03:24:08.413Z'),
      penulis: { connect: { user_id: 10 } },
      publishedAt: new Date('2025-05-04T03:24:08.329Z'),
      savedAt: new Date('2025-05-04T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.413Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-39". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 40,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-40',
      kategori: 'Serba Serbi',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-40. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+40' }],
      createdAt: new Date('2025-07-04T03:24:08.413Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-05-05T03:24:08.329Z'),
      savedAt: new Date('2025-05-05T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.413Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-40". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 41,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-41',
      kategori: 'Berita Daerah',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-41. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+41' }],
      createdAt: new Date('2025-07-04T03:24:08.415Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-05-06T03:24:08.329Z'),
      savedAt: new Date('2025-05-06T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.415Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-41". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 42,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-42',
      kategori: 'BPS Terkini',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-42. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+42' }],
      createdAt: new Date('2025-07-04T03:24:08.415Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-05-07T03:24:08.329Z'),
      savedAt: new Date('2025-05-07T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.415Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-42". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 43,
      judul: 'Wisata: Analisis Mendalam Topik ke-43',
      kategori: 'Wisata',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-43. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nurdjannah SST',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+43' }],
      createdAt: new Date('2025-07-04T03:24:08.417Z'),
      penulis: { connect: { user_id: 2 } },
      publishedAt: new Date('2025-05-08T03:24:08.329Z'),
      savedAt: new Date('2025-05-08T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.417Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-43". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 44,
      judul: 'Opini: Analisis Mendalam Topik ke-44',
      kategori: 'Opini',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-44. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+44' }],
      createdAt: new Date('2025-07-04T03:24:08.418Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-05-09T03:24:08.329Z'),
      savedAt: new Date('2025-05-09T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.418Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam T opik ke-44". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 45,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-45',
      kategori: 'Fotogenik',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-45. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+45' }],
      createdAt: new Date('2025-07-04T03:24:08.418Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-05-10T03:24:08.329Z'),
      savedAt: new Date('2025-05-10T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.418Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-45". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 46,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-46',
      kategori: 'Serba Serbi',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-46. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Dira Afiani S.S.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+46' }],
      createdAt: new Date('2025-07-04T03:24:08.419Z'),
      penulis: { connect: { user_id: 10 } },
      publishedAt: new Date('2025-05-11T03:24:08.329Z'),
      savedAt: new Date('2025-05-11T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.419Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-46". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 47,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-47',
      kategori: 'Berita Daerah',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-47. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aina Sabedah Fitri S.Si, MSE',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+47' }],
      createdAt: new Date('2025-07-04T03:24:08.420Z'),
      penulis: { connect: { user_id: 11 } },
      publishedAt: new Date('2025-05-12T03:24:08.329Z'),
      savedAt: new Date('2025-05-12T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.420Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-47". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 48,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-48',
      kategori: 'BPS Terkini',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-48. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Muhammad Haikal Candra S.Tr.Ds.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+48' }],
      createdAt: new Date('2025-07-04T03:24:08.421Z'),
      penulis: { connect: { user_id: 7 } },
      publishedAt: new Date('2025-05-13T03:24:08.329Z'),
      savedAt: new Date('2025-05-13T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.421Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-48". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 49,
      judul: 'Wisata: Analisis Mendalam Topik ke-49',
      kategori: 'Wisata',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-49. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+49' }],
      createdAt: new Date('2025-07-04T03:24:08.421Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-05-14T03:24:08.329Z'),
      savedAt: new Date('2025-05-14T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.421Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-49". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 50,
      judul: 'Opini: Analisis Mendalam Topik ke-50',
      kategori: 'Opini',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-50. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+50' }],
      createdAt: new Date('2025-07-04T03:24:08.422Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-05-15T03:24:08.329Z'),
      savedAt: new Date('2025-05-15T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.422Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-50". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 51,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-51',
      kategori: 'Fotogenik',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-51. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Andri Saleh S.Si, M.I.Kom.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+51' }],
      createdAt: new Date('2025-07-04T03:24:08.423Z'),
      penulis: { connect: { user_id: 6 } },
      publishedAt: new Date('2025-05-16T03:24:08.329Z'),
      savedAt: new Date('2025-05-16T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.423Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-51". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 52,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-52',
      kategori: 'Serba Serbi',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-52. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+52' }],
      createdAt: new Date('2025-07-04T03:24:08.423Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-05-17T03:24:08.329Z'),
      savedAt: new Date('2025-05-17T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.423Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-52". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 53,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-53',
      kategori: 'Berita Daerah',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-53. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nurdjannah SST',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+53' }],
      createdAt: new Date('2025-07-04T03:24:08.424Z'),
      penulis: { connect: { user_id: 2 } },
      publishedAt: new Date('2025-05-18T03:24:08.329Z'),
      savedAt: new Date('2025-05-18T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.424Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-53". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 54,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-54',
      kategori: 'BPS Terkini',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-54. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+54' }],
      createdAt: new Date('2025-07-04T03:24:08.424Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-05-19T03:24:08.329Z'),
      savedAt: new Date('2025-05-19T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.424Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-54". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 55,
      judul: 'Wisata: Analisis Mendalam Topik ke-55',
      kategori: 'Wisata',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-55. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Andri Saleh S.Si, M.I.Kom.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+55' }],
      createdAt: new Date('2025-07-04T03:24:08.425Z'),
      penulis: { connect: { user_id: 6 } },
      publishedAt: new Date('2025-05-20T03:24:08.329Z'),
      savedAt: new Date('2025-05-20T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.425Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-55". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 56,
      judul: 'Opini: Analisis Mendalam Topik ke-56',
      kategori: 'Opini',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-56. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+56' }],
      createdAt: new Date('2025-07-04T03:24:08.426Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-05-21T03:24:08.329Z'),
      savedAt: new Date('2025-05-21T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.426Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-56". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 57,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-57',
      kategori: 'Fotogenik',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-57. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+57' }],
      createdAt: new Date('2025-07-04T03:24:08.427Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-05-22T03:24:08.329Z'),
      savedAt: new Date('2025-05-22T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.427Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-57". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 58,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-58',
      kategori: 'Serba Serbi',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-58. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Andri Saleh S.Si, M.I.Kom.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+58' }],
      createdAt: new Date('2025-07-04T03:24:08.429Z'),
      penulis: { connect: { user_id: 6 } },
      publishedAt: new Date('2025-05-23T03:24:08.329Z'),
      savedAt: new Date('2025-05-23T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.429Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-58". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 59,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-59',
      kategori: 'Berita Daerah',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-59. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+59' }],
      createdAt: new Date('2025-07-04T03:24:08.430Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-05-24T03:24:08.329Z'),
      savedAt: new Date('2025-05-24T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.430Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-59". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 60,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-60',
      kategori: 'BPS Terkini',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-60. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+60' }],
      createdAt: new Date('2025-07-04T03:24:08.430Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-05-25T03:24:08.329Z'),
      savedAt: new Date('2025-05-25T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.430Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-60". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 61,
      judul: 'Wisata: Analisis Mendalam Topik ke-61',
      kategori: 'Wisata',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-61. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Mohamad Rivani S.IP, M.M.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+61' }],
      createdAt: new Date('2025-07-04T03:24:08.431Z'),
      penulis: { connect: { user_id: 5 } },
      publishedAt: new Date('2025-05-26T03:24:08.329Z'),
      savedAt: new Date('2025-05-26T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.431Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-61". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 62,
      judul: 'Opini: Analisis Mendalam Topik ke-62',
      kategori: 'Opini',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-62. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+62' }],
      createdAt: new Date('2025-07-04T03:24:08.432Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-05-27T03:24:08.329Z'),
      savedAt: new Date('2025-05-27T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.432Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-62". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 63,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-63',
      kategori: 'Fotogenik',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-63. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+63' }],
      createdAt: new Date('2025-07-04T03:24:08.432Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-05-28T03:24:08.329Z'),
      savedAt: new Date('2025-05-28T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.432Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-63". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 64,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-64',
      kategori: 'Serba Serbi',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-64. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Muhammad Haikal Candra S.Tr.Ds.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+64' }],
      createdAt: new Date('2025-07-04T03:24:08.435Z'),
      penulis: { connect: { user_id: 7 } },
      publishedAt: new Date('2025-05-29T03:24:08.329Z'),
      savedAt: new Date('2025-05-29T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.435Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-64". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 65,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-65',
      kategori: 'Berita Daerah',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-65. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+65' }],
      createdAt: new Date('2025-07-04T03:24:08.436Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-05-30T03:24:08.329Z'),
      savedAt: new Date('2025-05-30T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.436Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-65". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 66,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-66',
      kategori: 'BPS Terkini',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-66. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+66' }],
      createdAt: new Date('2025-07-04T03:24:08.436Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-05-31T03:24:08.329Z'),
      savedAt: new Date('2025-05-31T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.436Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-66". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 67,
      judul: 'Wisata: Analisis Mendalam Topik ke-67',
      kategori: 'Wisata',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-67. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Muhammad Haikal Candra S.Tr.Ds.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+67' }],
      createdAt: new Date('2025-07-04T03:24:08.437Z'),
      penulis: { connect: { user_id: 7 } },
      publishedAt: new Date('2025-06-01T03:24:08.329Z'),
      savedAt: new Date('2025-06-01T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.437Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-67". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 68,
      judul: 'Opini: Analisis Mendalam Topik ke-68',
      kategori: 'Opini',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-68. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+68' }],
      createdAt: new Date('2025-07-04T03:24:08.438Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-06-02T03:24:08.329Z'),
      savedAt: new Date('2025-06-02T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.438Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-68". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 69,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-69',
      kategori: 'Fotogenik',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-69. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+69' }],
      createdAt: new Date('2025-07-04T03:24:08.439Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-06-03T03:24:08.329Z'),
      savedAt: new Date('2025-06-03T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.439Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-69". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 70,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-70',
      kategori: 'Serba Serbi',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-70. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Dira Afiani S.S.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+70' }],
      createdAt: new Date('2025-07-04T03:24:08.440Z'),
      penulis: { connect: { user_id: 10 } },
      publishedAt: new Date('2025-06-04T03:24:08.329Z'),
      savedAt: new Date('2025-06-04T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.440Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-70". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 71,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-71',
      kategori: 'Berita Daerah',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-71. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+71' }],
      createdAt: new Date('2025-07-04T03:24:08.440Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-06-05T03:24:08.329Z'),
      savedAt: new Date('2025-06-05T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.440Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-71". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 72,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-72',
      kategori: 'BPS Terkini',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-72. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+72' }],
      createdAt: new Date('2025-07-04T03:24:08.441Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-06-06T03:24:08.329Z'),
      savedAt: new Date('2025-06-06T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.441Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-72". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 73,
      judul: 'Wisata: Analisis Mendalam Topik ke-73',
      kategori: 'Wisata',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-73. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Andri Saleh S.Si, M.I.Kom.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+73' }],
      createdAt: new Date('2025-07-04T03:24:08.442Z'),
      penulis: { connect: { user_id: 6 } },
      publishedAt: new Date('2025-06-07T03:24:08.329Z'),
      savedAt: new Date('2025-06-07T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.442Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-73". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 74,
      judul: 'Opini: Analisis Mendalam Topik ke-74',
      kategori: 'Opini',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-74. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+74' }],
      createdAt: new Date('2025-07-04T03:24:08.443Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-06-08T03:24:08.329Z'),
      savedAt: new Date('2025-06-08T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.443Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-74". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 75,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-75',
      kategori: 'Fotogenik',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-75. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Dira Afiani S.S.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+75' }],
      createdAt: new Date('2025-07-04T03:24:08.444Z'),
      penulis: { connect: { user_id: 10 } },
      publishedAt: new Date('2025-06-09T03:24:08.329Z'),
      savedAt: new Date('2025-06-09T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.444Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-75". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 76,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-76',
      kategori: 'Serba Serbi',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-76. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+76' }],
      createdAt: new Date('2025-07-04T03:24:08.444Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-06-10T03:24:08.329Z'),
      savedAt: new Date('2025-06-10T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.444Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-76". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 77,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-77',
      kategori: 'Berita Daerah',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-77. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+77' }],
      createdAt: new Date('2025-07-04T03:24:08.445Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-06-11T03:24:08.329Z'),
      savedAt: new Date('2025-06-11T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.445Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-77". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 78,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-78',
      kategori: 'BPS Terkini',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-78. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+78' }],
      createdAt: new Date('2025-07-04T03:24:08.446Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-06-12T03:24:08.329Z'),
      savedAt: new Date('2025-06-12T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.446Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-78". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 79,
      judul: 'Wisata: Analisis Mendalam Topik ke-79',
      kategori: 'Wisata',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-79. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+79' }],
      createdAt: new Date('2025-07-04T03:24:08.446Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-06-13T03:24:08.329Z'),
      savedAt: new Date('2025-06-13T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.446Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-79". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 80,
      judul: 'Opini: Analisis Mendalam Topik ke-80',
      kategori: 'Opini',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-80. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+80' }],
      createdAt: new Date('2025-07-04T03:24:08.447Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-06-14T03:24:08.329Z'),
      savedAt: new Date('2025-06-14T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.447Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-80". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 81,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-81',
      kategori: 'Fotogenik',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-81. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Andri Saleh S.Si, M.I.Kom.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+81' }],
      createdAt: new Date('2025-07-04T03:24:08.447Z'),
      penulis: { connect: { user_id: 6 } },
      publishedAt: new Date('2025-06-15T03:24:08.329Z'),
      savedAt: new Date('2025-06-15T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.447Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-81". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 82,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-82',
      kategori: 'Serba Serbi',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-82. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Mohamad Rivani S.IP, M.M.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+82' }],
      createdAt: new Date('2025-07-04T03:24:08.448Z'),
      penulis: { connect: { user_id: 5 } },
      publishedAt: new Date('2025-06-16T03:24:08.329Z'),
      savedAt: new Date('2025-06-16T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.448Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-82". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 83,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-83',
      kategori: 'Berita Daerah',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-83. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+83' }],
      createdAt: new Date('2025-07-04T03:24:08.448Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-06-17T03:24:08.329Z'),
      savedAt: new Date('2025-06-17T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.448Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-83". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 84,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-84',
      kategori: 'BPS Terkini',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-84. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+84' }],
      createdAt: new Date('2025-07-04T03:24:08.449Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-06-18T03:24:08.329Z'),
      savedAt: new Date('2025-06-18T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.449Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-84". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 85,
      judul: 'Wisata: Analisis Mendalam Topik ke-85',
      kategori: 'Wisata',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-85. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aina Sabedah Fitri S.Si, MSE',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+85' }],
      createdAt: new Date('2025-07-04T03:24:08.450Z'),
      penulis: { connect: { user_id: 11 } },
      publishedAt: new Date('2025-06-19T03:24:08.329Z'),
      savedAt: new Date('2025-06-19T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.450Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-85". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 86,
      judul: 'Opini: Analisis Mendalam Topik ke-86',
      kategori: 'Opini',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-86. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Andri Saleh S.Si, M.I.Kom.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+86' }],
      createdAt: new Date('2025-07-04T03:24:08.450Z'),
      penulis: { connect: { user_id: 6 } },
      publishedAt: new Date('2025-06-20T03:24:08.329Z'),
      savedAt: new Date('2025-06-20T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.450Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-86". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 87,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-87',
      kategori: 'Fotogenik',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-87. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+87' }],
      createdAt: new Date('2025-07-04T03:24:08.451Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-06-21T03:24:08.329Z'),
      savedAt: new Date('2025-06-21T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.451Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-87". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 88,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-88',
      kategori: 'Serba Serbi',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-88. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aina Sabedah Fitri S.Si, MSE',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+88' }],
      createdAt: new Date('2025-07-04T03:24:08.451Z'),
      penulis: { connect: { user_id: 11 } },
      publishedAt: new Date('2025-06-22T03:24:08.329Z'),
      savedAt: new Date('2025-06-22T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.451Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-88". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 89,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-89',
      kategori: 'Berita Daerah',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-89. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aliyah Salsabila Hakim S.Hum.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+89' }],
      createdAt: new Date('2025-07-04T03:24:08.453Z'),
      penulis: { connect: { user_id: 9 } },
      publishedAt: new Date('2025-06-23T03:24:08.329Z'),
      savedAt: new Date('2025-06-23T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.453Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-89". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 90,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-90',
      kategori: 'BPS Terkini',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-90. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+90' }],
      createdAt: new Date('2025-07-04T03:24:08.453Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-06-24T03:24:08.329Z'),
      savedAt: new Date('2025-06-24T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.453Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-90". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 91,
      judul: 'Wisata: Analisis Mendalam Topik ke-91',
      kategori: 'Wisata',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-91. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Muhammad Haikal Candra S.Tr.Ds.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+91' }],
      createdAt: new Date('2025-07-04T03:24:08.456Z'),
      penulis: { connect: { user_id: 7 } },
      publishedAt: new Date('2025-06-25T03:24:08.329Z'),
      savedAt: new Date('2025-06-25T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.456Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-91". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 92,
      judul: 'Opini: Analisis Mendalam Topik ke-92',
      kategori: 'Opini',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-92. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nur Laelatul Badriyah SE.AK, M.Si, CA',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+92' }],
      createdAt: new Date('2025-07-04T03:24:08.457Z'),
      penulis: { connect: { user_id: 3 } },
      publishedAt: new Date('2025-06-26T03:24:08.329Z'),
      savedAt: new Date('2025-06-26T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.457Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-92". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 93,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-93',
      kategori: 'Fotogenik',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-93. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+93' }],
      createdAt: new Date('2025-07-04T03:24:08.457Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: new Date('2025-06-27T03:24:08.329Z'),
      savedAt: new Date('2025-06-27T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.457Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-93". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 94,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-94',
      kategori: 'Serba Serbi',
      kata_kunci: ["Pariwisata", "Kebijakan"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-94. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Achmad Muchlis Abdi Putra SST., MT',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+94' }],
      createdAt: new Date('2025-07-04T03:24:08.458Z'),
      penulis: { connect: { user_id: 4 } },
      publishedAt: new Date('2025-06-28T03:24:08.329Z'),
      savedAt: new Date('2025-06-28T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.458Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-94". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 95,
      judul: 'Berita Daerah: Analisis Mendalam Topik ke-95',
      kategori: 'Berita Daerah',
      kata_kunci: ["Kebijakan", "Inovasi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-95. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nurdjannah SST',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+95' }],
      createdAt: new Date('2025-07-04T03:24:08.458Z'),
      penulis: { connect: { user_id: 2 } },
      publishedAt: new Date('2025-06-29T03:24:08.329Z'),
      savedAt: new Date('2025-06-29T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.458Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Berita Daerah: Analisis Mendalam Topik ke-95". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 96,
      judul: 'BPS Terkini: Analisis Mendalam Topik ke-96',
      kategori: 'BPS Terkini',
      kata_kunci: ["Inovasi", "Teknologi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-96. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aina Sabedah Fitri S.Si, MSE',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+96' }],
      createdAt: new Date('2025-07-04T03:24:08.459Z'),
      penulis: { connect: { user_id: 11 } },
      publishedAt: new Date('2025-06-30T03:24:08.329Z'),
      savedAt: new Date('2025-06-30T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.459Z'),
      abstrak: 'Ini adalah abstrak untuk berita "BPS Terkini: Analisis Mendalam Topik ke-96". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 97,
      judul: 'Wisata: Analisis Mendalam Topik ke-97',
      kategori: 'Wisata',
      kata_kunci: ["Teknologi", "Data"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-97. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Siti Nurdjannah SST',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+97' }],
      createdAt: new Date('2025-07-04T03:24:08.459Z'),
      penulis: { connect: { user_id: 2 } },
      publishedAt: new Date('2025-07-01T03:24:08.329Z'),
      savedAt: new Date('2025-07-01T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.459Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Wisata: Analisis Mendalam Topik ke-97". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 98,
      judul: 'Opini: Analisis Mendalam Topik ke-98',
      kategori: 'Opini',
      kata_kunci: ["Data", "Statistik"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-98. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Bagus Ardiansyah S.Tr.Stat.',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+98' }],
      createdAt: new Date('2025-07-04T03:24:08.460Z'),
      penulis: { connect: { user_id: 8 } },
      publishedAt: new Date('2025-07-02T03:24:08.329Z'),
      savedAt: new Date('2025-07-02T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.460Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Opini: Analisis Mendalam Topik ke-98". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 99,
      judul: 'Fotogenik: Analisis Mendalam Topik ke-99',
      kategori: 'Fotogenik',
      kata_kunci: ["Statistik", "Ekonomi"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-99. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aina Sabedah Fitri S.Si, MSE',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+99' }],
      createdAt: new Date('2025-07-04T03:24:08.460Z'),
      penulis: { connect: { user_id: 11 } },
      publishedAt: new Date('2025-07-03T03:24:08.329Z'),
      savedAt: new Date('2025-07-03T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.460Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Fotogenik: Analisis Mendalam Topik ke-99". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 100,
      judul: 'Serba Serbi: Analisis Mendalam Topik ke-100',
      kategori: 'Serba Serbi',
      kata_kunci: ["Ekonomi", "Pariwisata"],
      isi_berita: 'Ini adalah isi lengkap untuk berita ke-100. Pembahasan mencakup data historis, analisis tren, dan proyeksi masa depan untuk memberikan pemahaman yang komprehensif kepada pembaca.',
      status: 'published',
      nama_penulis: 'Aina Sabedah Fitri S.Si, MSE',
      gambar_urls: [{ url: 'https://placehold.co/1200x600/3B82F6/FFFFFF/png?text=Berita+100' }],
      createdAt: new Date('2025-07-04T03:24:08.461Z'),
      penulis: { connect: { user_id: 11 } },
      publishedAt: new Date('2025-07-04T03:24:08.329Z'),
      savedAt: new Date('2025-07-04T03:24:08.329Z'),
      updatedAt: new Date('2025-07-04T03:24:08.461Z'),
      abstrak: 'Ini adalah abstrak untuk berita "Serba Serbi: Analisis Mendalam Topik ke-100". Artikel ini membahas berbagai aspek penting yang relevan dengan topik terkini.',
    },
    {
      news_id: 1751605330468, // Gunakan BigInt literal jika memungkinkan, atau Number jika aman
      judul: 'emg bisa',
      kategori: '', // Dari dump kosong
      kata_kunci: [], // Dari dump kosong
      isi_berita: '<p>hey</p>',
      status: 'draft',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [{ url: '/files/berita/ufqm4y7d2th8wv9shd1xuph5z.27.33.png' }],
      createdAt: new Date('2025-07-04T05:02:10.545Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: null, // null jika DUMP nya NULL
      savedAt: new Date('2025-07-04T05:02:10.468Z'),
      updatedAt: new Date('2025-07-04T05:02:10.545Z'),
      abstrak: '', // Dari dump kosong
    },
    {
      news_id: 1751606827664,
      judul: 'uda bisa blm',
      kategori: 'BPS Terkini',
      kata_kunci: [],
      isi_berita: '<p>aaaaa</p>',
      status: 'draft',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [
        { url: '/files/berita/f2qa760qwp2ufxq05dkgoalug.27.33.png' },
        { url: '/files/berita/on7x8x2puan2igdoxrjb0j6sw.13.35.png' },
        { url: '/files/berita/u9xec0zudfs700f7enytw7t28.42.23.png' }
      ],
      createdAt: new Date('2025-07-04T05:27:07.686Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: null,
      savedAt: new Date('2025-07-04T05:27:07.664Z'),
      updatedAt: new Date('2025-07-04T05:27:07.686Z'),
      abstrak: 'ini bsia gaa',
    },
    {
      news_id: 1751606831424,
      judul: 'uda bisa blm',
      kategori: 'BPS Terkini',
      kata_kunci: [],
      isi_berita: '<p>aaaaa</p>',
      status: 'pending_review',
      nama_penulis: 'Arianto S.Si., SE., M.Si',
      gambar_urls: [
        { url: '/files/berita/lj8588ddn2shihrssusa68bxr.27.33.png' },
        { url: '/files/berita/jepu8amd28e41ao5rrvv1iqpb.13.35.png' },
        { url: '/files/berita/z9nannvp3g7d27p1uj24mcdyt.42.23.png' }
      ],
      createdAt: new Date('2025-07-04T05:27:11.426Z'),
      penulis: { connect: { user_id: 1 } },
      publishedAt: null,
      savedAt: new Date('2025-07-04T05:27:11.424Z'),
      updatedAt: new Date('2025-07-04T05:27:11.426Z'),
      abstrak: 'ini bsia gaa',
    },
  ];

  for (const data of newsData) {
    await prisma.news.upsert({
      where: { news_id: data.news_id },
      update: data,
      create: data,
    });
  }
  console.log(`✅ Seeded news.`);
}